### ISSUE TITLE
Significant bugs and pointless code in the repo.

### ISSUE THREAD

**Issue by haxys** [r2dr0dn/Cryptz#3]
This script wastes users' time with pointless loading screens, hard-coded registration keys, and half-baked or broken functionality.

I've gone over the code to improve it significantly, and I've issued a pull request to fix these problems.

**Comment by haxys** [comment]
See [the pull request](https://github.com/r2dr0dn/Cryptz/pull/1) for more information.

**Comment by M1ndo** [comment]
Thanks Alot Again For Ur Hard Work On Cryptz.
